// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/cms_runtime/v1/runtime.proto

package cmsruntimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvaluateRequest carries all data needed for evaluation.
// The caller (cms-delivery) is responsible for querying the database.
type EvaluateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Placement name being evaluated, e.g. "hero" or "banner_top".
	PlacementName string `protobuf:"bytes,1,opt,name=placement_name,json=placementName,proto3" json:"placement_name,omitempty"`
	// JSON-serialised []entity.Schedule with preloaded DecisionRule,
	// Placement, RuleConditions (+ Attribute), and Rules (+ RuleAttributes).
	// JSON bytes avoid duplicating the complex entity graph in proto.
	SchedulesJson []byte `protobuf:"bytes,2,opt,name=schedules_json,json=schedulesJson,proto3" json:"schedules_json,omitempty"`
	// JSON-serialised live user attrs: attributeID -> compact JSON value.
	// Non-empty means resolve ranked results. Empty means return logic
	// entries for delivery-time evaluation.
	UserAttrsJson []byte `protobuf:"bytes,3,opt,name=user_attrs_json,json=userAttrsJson,proto3" json:"user_attrs_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_proto_cms_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_proto_cms_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetPlacementName() string {
	if x != nil {
		return x.PlacementName
	}
	return ""
}

func (x *EvaluateRequest) GetSchedulesJson() []byte {
	if x != nil {
		return x.SchedulesJson
	}
	return nil
}

func (x *EvaluateRequest) GetUserAttrsJson() []byte {
	if x != nil {
		return x.UserAttrsJson
	}
	return nil
}

// Campaign carries campaign metadata for AUDIENCE / SALES_TARGET rule types.
type Campaign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_proto_cms_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_proto_cms_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Campaign) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Campaign) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Campaign) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// ContentResult is a single evaluated and ranked content item.
type ContentResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContentPath    string                 `protobuf:"bytes,1,opt,name=content_path,json=contentPath,proto3" json:"content_path,omitempty"`
	DecisionRuleId string                 `protobuf:"bytes,2,opt,name=decision_rule_id,json=decisionRuleId,proto3" json:"decision_rule_id,omitempty"`
	RuleSetType    string                 `protobuf:"bytes,3,opt,name=rule_set_type,json=ruleSetType,proto3" json:"rule_set_type,omitempty"`
	Source         string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Score          float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	Variation      *string                `protobuf:"bytes,6,opt,name=variation,proto3,oneof" json:"variation,omitempty"`
	StartDateTime  string                 `protobuf:"bytes,7,opt,name=start_date_time,json=startDateTime,proto3" json:"start_date_time,omitempty"`
	EndDateTime    string                 `protobuf:"bytes,8,opt,name=end_date_time,json=endDateTime,proto3" json:"end_date_time,omitempty"`
	Campaign       *Campaign              `protobuf:"bytes,9,opt,name=campaign,proto3,oneof" json:"campaign,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContentResult) Reset() {
	*x = ContentResult{}
	mi := &file_proto_cms_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentResult) ProtoMessage() {}

func (x *ContentResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentResult.ProtoReflect.Descriptor instead.
func (*ContentResult) Descriptor() ([]byte, []int) {
	return file_proto_cms_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *ContentResult) GetContentPath() string {
	if x != nil {
		return x.ContentPath
	}
	return ""
}

func (x *ContentResult) GetDecisionRuleId() string {
	if x != nil {
		return x.DecisionRuleId
	}
	return ""
}

func (x *ContentResult) GetRuleSetType() string {
	if x != nil {
		return x.RuleSetType
	}
	return ""
}

func (x *ContentResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContentResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ContentResult) GetVariation() string {
	if x != nil && x.Variation != nil {
		return *x.Variation
	}
	return ""
}

func (x *ContentResult) GetStartDateTime() string {
	if x != nil {
		return x.StartDateTime
	}
	return ""
}

func (x *ContentResult) GetEndDateTime() string {
	if x != nil {
		return x.EndDateTime
	}
	return ""
}

func (x *ContentResult) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

// EvaluateResponse carries JSON-serialised PlacementLogicEntry
// records. Using bytes avoids duplicating the full domain model in proto.
type EvaluateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-serialised []domainservice.PlacementLogicEntry.
	LogicEntriesJson []byte `protobuf:"bytes,1,opt,name=logic_entries_json,json=logicEntriesJson,proto3" json:"logic_entries_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_proto_cms_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cms_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_proto_cms_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluateResponse) GetLogicEntriesJson() []byte {
	if x != nil {
		return x.LogicEntriesJson
	}
	return nil
}

var File_proto_cms_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_proto_cms_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\"proto/cms_runtime/v1/runtime.proto\x12\x0ecms_runtime.v1\"\x87\x01\n" +
	"\x0fEvaluateRequest\x12%\n" +
	"\x0eplacement_name\x18\x01 \x01(\tR\rplacementName\x12%\n" +
	"\x0eschedules_json\x18\x02 \x01(\fR\rschedulesJson\x12&\n" +
	"\x0fuser_attrs_json\x18\x03 \x01(\fR\ruserAttrsJson\"X\n" +
	"\bCampaign\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\xf3\x02\n" +
	"\rContentResult\x12!\n" +
	"\fcontent_path\x18\x01 \x01(\tR\vcontentPath\x12(\n" +
	"\x10decision_rule_id\x18\x02 \x01(\tR\x0edecisionRuleId\x12\"\n" +
	"\rrule_set_type\x18\x03 \x01(\tR\vruleSetType\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12!\n" +
	"\tvariation\x18\x06 \x01(\tH\x00R\tvariation\x88\x01\x01\x12&\n" +
	"\x0fstart_date_time\x18\a \x01(\tR\rstartDateTime\x12\"\n" +
	"\rend_date_time\x18\b \x01(\tR\vendDateTime\x129\n" +
	"\bcampaign\x18\t \x01(\v2\x18.cms_runtime.v1.CampaignH\x01R\bcampaign\x88\x01\x01B\f\n" +
	"\n" +
	"_variationB\v\n" +
	"\t_campaign\"@\n" +
	"\x10EvaluateResponse\x12,\n" +
	"\x12logic_entries_json\x18\x01 \x01(\fR\x10logicEntriesJson2b\n" +
	"\x11CMSRuntimeService\x12M\n" +
	"\bEvaluate\x12\x1f.cms_runtime.v1.EvaluateRequest\x1a .cms_runtime.v1.EvaluateResponseB9Z7kbank-ecms/internal/grpc/pb/cms_runtime/v1;cmsruntimev1b\x06proto3"

var (
	file_proto_cms_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_proto_cms_runtime_v1_runtime_proto_rawDescData []byte
)

func file_proto_cms_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_proto_cms_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_proto_cms_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cms_runtime_v1_runtime_proto_rawDesc), len(file_proto_cms_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_proto_cms_runtime_v1_runtime_proto_rawDescData
}

var file_proto_cms_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_cms_runtime_v1_runtime_proto_goTypes = []any{
	(*EvaluateRequest)(nil),  // 0: cms_runtime.v1.EvaluateRequest
	(*Campaign)(nil),         // 1: cms_runtime.v1.Campaign
	(*ContentResult)(nil),    // 2: cms_runtime.v1.ContentResult
	(*EvaluateResponse)(nil), // 3: cms_runtime.v1.EvaluateResponse
}
var file_proto_cms_runtime_v1_runtime_proto_depIdxs = []int32{
	1, // 0: cms_runtime.v1.ContentResult.campaign:type_name -> cms_runtime.v1.Campaign
	0, // 1: cms_runtime.v1.CMSRuntimeService.Evaluate:input_type -> cms_runtime.v1.EvaluateRequest
	3, // 2: cms_runtime.v1.CMSRuntimeService.Evaluate:output_type -> cms_runtime.v1.EvaluateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_cms_runtime_v1_runtime_proto_init() }
func file_proto_cms_runtime_v1_runtime_proto_init() {
	if File_proto_cms_runtime_v1_runtime_proto != nil {
		return
	}
	file_proto_cms_runtime_v1_runtime_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cms_runtime_v1_runtime_proto_rawDesc), len(file_proto_cms_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cms_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_proto_cms_runtime_v1_runtime_proto_depIdxs,
		MessageInfos:      file_proto_cms_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_proto_cms_runtime_v1_runtime_proto = out.File
	file_proto_cms_runtime_v1_runtime_proto_goTypes = nil
	file_proto_cms_runtime_v1_runtime_proto_depIdxs = nil
}
