// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/cms_runtime/v1/runtime.proto

package cmsruntimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CMSRuntimeService_Evaluate_FullMethodName = "/cms_runtime.v1.CMSRuntimeService/Evaluate"
)

// CMSRuntimeServiceClient is the client API for CMSRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CMSRuntimeService exposes cms-runtime's rule evaluation engine over gRPC.
// cms-delivery calls this on a cache miss to trigger on-demand evaluation.
type CMSRuntimeServiceClient interface {
	// Evaluate returns cached logic entries when user attrs are empty.
	// With user attrs present, it resolves ranked results and keeps the
	// legacy rule.Score fallback when no variation matches.
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
}

type cMSRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCMSRuntimeServiceClient(cc grpc.ClientConnInterface) CMSRuntimeServiceClient {
	return &cMSRuntimeServiceClient{cc}
}

func (c *cMSRuntimeServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, CMSRuntimeService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CMSRuntimeServiceServer is the server API for CMSRuntimeService service.
// All implementations must embed UnimplementedCMSRuntimeServiceServer
// for forward compatibility.
//
// CMSRuntimeService exposes cms-runtime's rule evaluation engine over gRPC.
// cms-delivery calls this on a cache miss to trigger on-demand evaluation.
type CMSRuntimeServiceServer interface {
	// Evaluate returns cached logic entries when user attrs are empty.
	// With user attrs present, it resolves ranked results and keeps the
	// legacy rule.Score fallback when no variation matches.
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	mustEmbedUnimplementedCMSRuntimeServiceServer()
}

// UnimplementedCMSRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCMSRuntimeServiceServer struct{}

func (UnimplementedCMSRuntimeServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedCMSRuntimeServiceServer) mustEmbedUnimplementedCMSRuntimeServiceServer() {}
func (UnimplementedCMSRuntimeServiceServer) testEmbeddedByValue()                           {}

// UnsafeCMSRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CMSRuntimeServiceServer will
// result in compilation errors.
type UnsafeCMSRuntimeServiceServer interface {
	mustEmbedUnimplementedCMSRuntimeServiceServer()
}

func RegisterCMSRuntimeServiceServer(s grpc.ServiceRegistrar, srv CMSRuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedCMSRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CMSRuntimeService_ServiceDesc, srv)
}

func _CMSRuntimeService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CMSRuntimeServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CMSRuntimeService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CMSRuntimeServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CMSRuntimeService_ServiceDesc is the grpc.ServiceDesc for CMSRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CMSRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cms_runtime.v1.CMSRuntimeService",
	HandlerType: (*CMSRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _CMSRuntimeService_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cms_runtime/v1/runtime.proto",
}
