version: "2"

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(kbank-ecms)
      custom-order: true

linters:
  disable:
    - errcheck
