services:
  svc-contstrat-strategy:
    build: .
    command: [ "./server" ]
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      SETENV: DEVLOCAL
      DB_HOST: postgres
      REDIS_HOST: redis
      SWAGGER_HOST: localhost:8082
    networks:
      - aks
      - cmc-backend

networks:
  aks:
    driver: bridge
  cmc-backend:
    external: true
    name: cmc-backend
