// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
	"kbank-ecms/cmd/svc-contstrat-backoffice/handler"
	"kbank-ecms/internal/domain/entity"
	"kbank-ecms/internal/repository"
	"kbank-ecms/internal/service"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies to construct the Gin engine.
func InitializeApp(db *gorm.DB, rateLimit entity.RateLimit) (*gin.Engine, error) {
	ruleManagementService := service.NewRuleManagementService()
	ruleManagementHandler := handler.NewRuleManagementHandler(ruleManagementService)
	schedulePostgresRepository := repository.NewSchedulePostgresRepository(db)
	scheduleService := service.NewScheduleService(schedulePostgresRepository)
	scheduleHandler := handler.NewScheduleHandler(scheduleService)
	decisionRulePostgresRepository := repository.NewDecisionRulePostgresRepository(db)
	decisionRuleService := service.NewDecisionRuleService(decisionRulePostgresRepository)
	decisionRuleHandler := handler.NewDecisionRuleHandler(decisionRuleService)
	engine := ProvideRouter(db, rateLimit, ruleManagementHandler, scheduleHandler, decisionRuleHandler)
	return engine, nil
}
