// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"kbank-ecms/cmd/svc-contstrat-backoffice/handler"
	"kbank-ecms/internal/domain/entity"
	"kbank-ecms/internal/repository"
	"kbank-ecms/internal/service"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies and returns the Application bundle
// (Gin engine + background occurrence worker).
func InitializeApp(db *gorm.DB, rateLimit entity.RateLimit) (*Application, error) {
	ruleManagementService := service.NewRuleManagementService()
	ruleManagementHandler := handler.NewRuleManagementHandler(ruleManagementService)
	schedulePostgresRepository := repository.NewSchedulePostgresRepository(db)
	scheduleService := service.NewScheduleService(schedulePostgresRepository)
	scheduleHandler := handler.NewScheduleHandler(scheduleService)
	decisionRulePostgresRepository := repository.NewDecisionRulePostgresRepository(db)
	decisionRuleService := service.NewDecisionRuleService(decisionRulePostgresRepository)
	decisionRuleHandler := handler.NewDecisionRuleHandler(decisionRuleService)
	decisionRuleWizardPostgresRepository := repository.NewDecisionRuleWizardPostgresRepository(db)
	attributePostgresRepository := repository.NewAttributePostgresRepository(db)
	placementPostgresRepository := repository.NewPlacementPostgresRepository(db)
	decisionRuleWizardService := service.NewDecisionRuleWizardService(decisionRuleWizardPostgresRepository, attributePostgresRepository, placementPostgresRepository)
	decisionRuleWizardHandler := handler.NewDecisionRuleWizardHandler(decisionRuleWizardService)
	scheduleOccurrencePostgresRepository := repository.NewScheduleOccurrencePostgresRepository(db)
	scheduleOccurrenceService := service.NewScheduleOccurrenceService(scheduleOccurrencePostgresRepository)
	scheduleOccurrenceHandler := handler.NewScheduleOccurrenceHandler(scheduleOccurrenceService)
	attributeService := service.NewAttributeService(attributePostgresRepository)
	attributeHandler := handler.NewAttributeHandler(attributeService)
	channelPostgresRepository := repository.NewChannelPostgresRepository(db)
	channelService := service.NewChannelService(channelPostgresRepository)
	channelHandler := handler.NewChannelHandler(channelService)
	placementService := service.NewPlacementService(placementPostgresRepository)
	placementHandler := handler.NewPlacementHandler(placementService)
	engine := ProvideRouter(db, rateLimit, ruleManagementHandler, scheduleHandler, decisionRuleHandler, decisionRuleWizardHandler, scheduleOccurrenceHandler, attributeHandler, channelHandler, placementHandler)
	materializationConfig := ProvideMatConfig()
	scheduleMaterializationService := service.NewScheduleMaterializationService(materializationConfig, schedulePostgresRepository, scheduleOccurrencePostgresRepository)
	occurrenceWorkerConfig := ProvideWorkerConfig()
	occurrenceWorker := service.NewOccurrenceWorker(scheduleMaterializationService, occurrenceWorkerConfig)
	application := NewApplication(engine, occurrenceWorker)
	return application, nil
}
