// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"kbank-ecms/internal/domain/entity"
	"kbank-ecms/internal/domain/repository"
	"kbank-ecms/internal/domain/service"
	repository2 "kbank-ecms/internal/repository"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies to construct the delivery service and Gin engine.
func InitializeApp(db *gorm.DB, rateLimit entity.RateLimit, redisRepo repository.RedisCacheRepository, evaluator service.RuntimeEvaluator) (*App, func()) {
	schedulePostgresRepository := repository2.NewSchedulePostgresRepository(db)
	cacheMemory, cleanup := ProvideCacheMemory()
	cmsDeliveryService := ProvideCMSDeliveryService(redisRepo, schedulePostgresRepository, evaluator, cacheMemory)
	engine := ProvideRouter(db, rateLimit, cmsDeliveryService)
	app := ProvideApp(engine, cmsDeliveryService)
	return app, func() {
		cleanup()
	}
}
