// Package server Code generated by swaggo/swag. DO NOT EDIT
package server

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/content-strategy/v1/personalized-content": {
            "get": {
                "description": "Returns evaluated content results for one or more placement names.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "svc-contstrat-delivery"
                ],
                "summary": "Get content by placements",
                "parameters": [
                    {
                        "enum": [
                            "personalizedContent",
                            "staticContent",
                            "articleCategory"
                        ],
                        "type": "string",
                        "description": "The type of content request",
                        "name": "requestType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "knownContent",
                            "logicalBased",
                            "contentType",
                            "articleCategory"
                        ],
                        "type": "string",
                        "description": "The mode of content request",
                        "name": "mode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "WAMP",
                        "description": "Channel",
                        "name": "channel",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "default": "wsaHomeBanner, wsaPortBanner, wsaTransaction",
                        "description": "One or more placement names",
                        "name": "placement",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Customer identifier value (required when customerIdType=CIS_ID)",
                        "name": "customerId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "CIS_ID",
                            "IP_ID",
                            "KPLUS_MOBILE_NUMBER",
                            "LINE_UUID"
                        ],
                        "type": "string",
                        "default": "CIS_ID",
                        "description": "Customer identifier scheme",
                        "name": "customerIdType",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Number of results per page",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.ContentResult"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/content-strategy/v1/purge_requests": {
            "get": {
                "description": "Returns in-memory cache keys, heap pressure flag, and heap usage ratio.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "svc-contstrat-delivery"
                ],
                "summary": "Get cache status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.CacheStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Flushes the cache for specified placements. An empty or missing body flushes all placements.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "svc-contstrat-delivery"
                ],
                "summary": "Flush content cache",
                "parameters": [
                    {
                        "description": "Placements to flush; omit to flush all",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.FlushRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.FlushResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/content-strategy/v1/purge_requests/value": {
            "get": {
                "description": "Returns the cached value for a given key. Used for monitoring and debugging.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "svc-contstrat-delivery"
                ],
                "summary": "Get cache value",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The cache key to retrieve",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "type": "integer"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "kbank-ecms_internal_delivery_http_dto.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "error": {
                    "type": "string"
                },
                "pagination": {
                    "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.Pagination"
                }
            }
        },
        "kbank-ecms_internal_delivery_http_dto.CacheStatusResponse": {
            "type": "object",
            "properties": {
                "cacheKeys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "isMemPressure": {
                    "type": "boolean"
                },
                "memoryUsagePct": {
                    "type": "number"
                }
            }
        },
        "kbank-ecms_internal_delivery_http_dto.Campaign": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                }
            }
        },
        "kbank-ecms_internal_delivery_http_dto.ContentResult": {
            "type": "object",
            "properties": {
                "campaign": {
                    "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.Campaign"
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/kbank-ecms_internal_delivery_http_dto.LogicCondition"
                    }
                },
                "contentPath": {
                    "type": "string"
                },
                "decisionRuleId": {
                    "type": "string"
                },
                "endDateTime": {
                    "type": "string"
                },
                "logicEval": {
                    "description": "Evaluation result of the logic expression; present for logic cache entries",
                    "type": "boolean"
                },
                "logicExpr": {
                    "description": "Human-readable expression; present for logic cache entries",
                    "type": "string"
                },
                "logicHash": {
                    "description": "Stable SHA-256 hash; present for logic cache entries",
                    "type": "string"
                },
                "ruleSetType": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "source": {
                    "type": "string"
                },
                "startDateTime": {
                    "type": "string"
                }
            }
        },
        "kbank-ecms_internal_delivery_http_dto.FlushRequest": {
            "type": "object",
            "properties": {
                "isEvaluate": {
                    "description": "Optional flag to trigger cache re-population after flush",
                    "type": "boolean"
                },
                "placements": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "kbank-ecms_internal_delivery_http_dto.FlushResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "kbank-ecms_internal_delivery_http_dto.LogicCondition": {
            "type": "object",
            "properties": {
                "attributeId": {
                    "type": "string"
                },
                "childConnectorOperator": {
                    "description": "joins own leaf check with children-group",
                    "type": "string"
                },
                "conditionId": {
                    "type": "string"
                },
                "connectorOperator": {
                    "description": "forward-link to next sibling",
                    "type": "string"
                },
                "dataType": {
                    "type": "string"
                },
                "expectedValue": {
                    "description": "compact JSON from RuleAttribute.Value",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "logicalOperator": {
                    "type": "string"
                },
                "parentConditionId": {
                    "description": "empty = root",
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                }
            }
        },
        "kbank-ecms_internal_delivery_http_dto.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "totalItems": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "KBank ECMS CMS Delivery API",
	Description:      "Backend API for KBank ECMS CMS Delivery Runtime Service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
