// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"kbank-ecms/internal/domain/entity"
	"kbank-ecms/internal/domain/repository"
	repository2 "kbank-ecms/internal/repository"

	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies to construct the delivery service and Gin engine.
func InitializeApp(db *gorm.DB, redisRepo repository.RedisCacheRepository, rateLimit entity.RateLimit) (*App, func()) {
	scheduleOccurrencePostgresRepository := repository2.NewScheduleOccurrencePostgresRepository(db)
	decisionRulePostgresRepository := repository2.NewDecisionRulePostgresRepository(db)
	cacheMemory, cleanup := ProvideCacheMemory()
	localEvaluator := ProvideRuntimeEvaluator()
	cmsDeliveryService := ProvideCMSDeliveryService(redisRepo, scheduleOccurrencePostgresRepository, decisionRulePostgresRepository, localEvaluator, cacheMemory)
	engine := ProvideRouter(db, rateLimit, cmsDeliveryService)
	app := ProvideApp(engine, cmsDeliveryService)
	return app, func() {
		cleanup()
	}
}
