// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"kbank-ecms/internal/domain/entity"
	"kbank-ecms/internal/repository"
)

// Injectors from wire.go:

// InitializeApp wires all dependencies to construct the delivery service and Gin engine.
func InitializeApp(db *gorm.DB, redisRepo *repository.RedisRepository, rateLimit entity.RateLimit) (*App, func()) {
	scheduleOccurrencePostgresRepository := repository.NewScheduleOccurrencePostgresRepository(db)
	decisionRulePostgresRepository := repository.NewDecisionRulePostgresRepository(db)
	localEvaluator := ProvideRuntimeEvaluator()
	memoryCache, cleanup := ProvideCacheMemory()
	cmsDeliveryService := ProvideCMSDeliveryService(redisRepo, scheduleOccurrencePostgresRepository, decisionRulePostgresRepository, localEvaluator, memoryCache)
	engine := ProvideRouter(db, rateLimit, redisRepo, cmsDeliveryService)
	app := ProvideApp(engine, cmsDeliveryService)
	return app, func() {
		cleanup()
	}
}
