newservice:
  name: "rule-management"
  log_level: "info"

server:
- name: "RULE_MANAGEMENT"
  endpoint: "http://localhost:8080"
  servicebreaker: 5
  timeout: 5
  retries: 2
  ratelimit:
    requests_per_second: 50
    burst: 100
    max_concurrent_requests: 10
  transform:
    enabled: false
    rules: []
  reponsedefault:
    enabled: false
    status_code: 200
    body: '{"message": "Service unavailable, using default"}'
