#!/usr/bin/env sh
# Seed Redis with sample CIS user attributes for local development / testing.
# AUTO-GENERATED by scripts/mockdata — do not edit manually.
# Regenerate: make db-mock-generate-decision-rule
#
# Key format  : cis_id:{cisID}
# Value format: JSON object keyed by attribute UUIDs
#
# Attribute UUIDs (from this generation):
#   segment    e50751ea-bf83-438f-8a8c-d755796e7925  Text   Mass | Affluent | VIP | Young Wealth | SME
#   user_age   fba03e8e-8dfb-4b32-b8b8-f5213ac98d46  Number
#   region     6c98514c-3374-4be8-88fc-561bc5831cbc  Text   Bangkok | Central | North | Northeast | South
#   risk_level 1acbc057-ccf7-47db-afb9-2a67e08f8ebe  Number 1..5

REDIS_CLI="${REDIS_CLI:-redis-cli}"

set -e

seed() {
  CIS_ID="$1"
  PAYLOAD="$2"
  $REDIS_CLI SET "cis_id:${CIS_ID}" "${PAYLOAD}"
  echo "  SET cis_id:${CIS_ID}"
}

echo "Seeding Redis user attributes..."

# Mass / Bangkok / age 28 / risk 2 — baseline mass user
seed "0000000001" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":2,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Bangkok\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Mass\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":28}"

# Affluent / Central / age 35 / risk 3 — mid-risk affluent
seed "0000000002" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":3,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Central\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Affluent\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":35}"

# VIP / North / age 45 / risk 4 — high-risk VIP
seed "0000000003" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":4,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"North\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"VIP\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":45}"

# Young Wealth / Northeast / age 24 / risk 1 — low-risk young
seed "0000000004" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":1,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Northeast\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Young Wealth\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":24}"

# SME / South / age 52 / risk 5 — max-risk SME
seed "0000000005" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":5,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"South\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"SME\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":52}"

# Mass / Northeast / age 60 / risk 2 — senior user triggering age >= rules
seed "0000000006" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":2,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Northeast\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Mass\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":60}"

# Affluent / South / age 20 / risk 1 — youngest legal user
seed "0000000007" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":1,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"South\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Affluent\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":20}"

# VIP / Bangkok / age 65 / risk 5 — oldest+max risk
seed "0000000008" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":5,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Bangkok\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"VIP\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":65}"

# Young Wealth / Central / age 22 / risk 5 — young but high risk
seed "0000000009" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":5,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Central\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Young Wealth\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":22}"

# SME / North / age 48 / risk 1 — risk-averse SME
seed "0000000010" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":1,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"North\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"SME\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":48}"

# Mass / Bangkok / age 33 / risk 3
seed "0000000011" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":3,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Bangkok\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Mass\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":33}"

# Affluent / Bangkok / age 40 / risk 4
seed "0000000012" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":4,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Bangkok\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Affluent\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":40}"

# VIP / Bangkok / age 55 / risk 2 — low-risk VIP
seed "0000000013" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":2,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Bangkok\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"VIP\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":55}"

# SME / Central / age 42 / risk 3
seed "0000000014" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":3,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Central\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"SME\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":42}"

# Mass / Central / age 50 / risk 5
seed "0000000015" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":5,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Central\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Mass\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":50}"

# Young Wealth / North / age 29 / risk 2
seed "0000000016" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":2,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"North\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Young Wealth\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":29}"

# Affluent / Northeast / age 38 / risk 4
seed "0000000017" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":4,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Northeast\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Affluent\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":38}"

# VIP / South / age 47 / risk 3
seed "0000000018" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":3,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"South\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"VIP\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":47}"

# Mass / Bangkok / age 30 / risk 3 — common age threshold
seed "0000000019" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":3,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Bangkok\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"Mass\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":30}"

# SME / Northeast / age 56 / risk 4 — senior SME triggering age >= 56 rules
seed "0000000020" "{\"1acbc057-ccf7-47db-afb9-2a67e08f8ebe\":4,\"6c98514c-3374-4be8-88fc-561bc5831cbc\":\"Northeast\",\"e50751ea-bf83-438f-8a8c-d755796e7925\":\"SME\",\"fba03e8e-8dfb-4b32-b8b8-f5213ac98d46\":56}"

echo "Done. Seeded 20 CIS user attribute records."
