name: Remove Stale Branches

on:
  schedule:
    - cron: "0 2 * * 1" # Every Monday at 02:00 UTC
  workflow_dispatch:

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - uses: crs-k/stale-branches@v9.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-delete: 90
          dry-run: false
          branches-filter-regex: "^((?!kbank-production))"
